### ISSUE TITLE
`neuromorpho` package metadata outdated

### ISSUE THREAD

**Issue by Helveg** [stephanmg/stephanmg#1]
Hi,

https://pypi.org/project/neuromorpho/ has a `Homepage` to https://github.com/stephanmg/neuromorpho, which doesn't exist anymore.

Could you upload a [post release](https://peps.python.org/pep-0440/#post-releases) that points to the new homepage and issue tracker?

**Comment by stephanmg** [comment]
https://github.com/NeuroBox3D/neuromorpho

**Comment by Helveg** [comment]
Right, but https://pypi.org/project/neuromorpho/ still lists it incorrectly 😇

**Comment by stephanmg** [comment]
Okay, sorry for this. Metadata should now be corrected in release `v0.0.3`.
